### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by kysrpex** [usegalaxy-eu/website#1124]
I was trying to fix Dependabot (#1120), but while doing so I found several other issues.

- Local builds do not work. This should be fixed by #1123.
- There is something wrong with #1119. Jenkins builds the website for commit e901e09, but fails for 8aef002: ``Liquid Exception: undefined method `numeric?' for nil:NilClass in citations.md``. I created #1125 to fix it temporarily.
- There has been an additional issue impeding Jenkins from building the website since the first of July, `CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic`. Probably related to the [libmamba rollout](https://conda.org/blog/2023-07-05-conda-libmamba-solver-rollout/). I just added `conda config --set solver classic` to Jenkins.

**Comment by kysrpex** [comment]
From the two citations introduced in 8aef002, I narrowed it down to this one.

```bibtex
@misc{noauthor_ijms_nodate,
 keywords = {{\textgreater}UseGalaxy.eu},
 title = {{IJMS} {\textbar} {Free} {Full}-{Text} {\textbar} {Meta}-{Analysis} of {Mechano}-{Sensitive} {Ion} {Channels} in {Human} {Hearts}: {Chamber}- and {Disease}-{Preferential} {mRNA} {Expression}},
 url = {https://www.mdpi.com/1422-0067/24/13/10961},
 urldate = {2023-07-05}
}
```
